name: Check-pull-request-title-and-description

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  Check-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Check the pull request
        uses: mristin/opinionated-commit-message@v2.3.1
        with:
          path-to-additional-verbs: additional-verbs-in-imperative-mood.txt

      - name: READ HERE ON FAILURE FOR MORE INSTRUCTIONS
        if: ${{ failure() }}
        run: |
          echo \
            "The title and the description of your pull request do not fit our style guide." \
            "Please inspect carefully the error messages above and edit the pull request." \
            "See the contributing guidelines at: " \
            "https://github.com/aas-core-works/aas-core-meta/blob/master/doc/contributing.md#write-commit-message"
